/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student_bd;

import java.awt.Component;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;

import java.text.MessageFormat;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableColumn;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

/**
 *
 * @author Егор
 */
public class Student_BD extends javax.swing.JFrame {

    String username = "root";
    String password = "2041988VikaNika";
    String dataCon = "jdbc:mysql://localhost:3306/resultdb?serverTimezone=Europe/Moscow";

    Connection sqlCon = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    int q, i;

    public Student_BD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void uploadDB() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlCon = DriverManager.getConnection(dataCon, username, password);
            pst = sqlCon.prepareStatement("select * from resultdb");
            rs = pst.executeQuery();
            ResultSetMetaData stData = rs.getMetaData();

            q = stData.getColumnCount();

            DefaultTableModel RecordTable = (DefaultTableModel) jTable1.getModel();
            RecordTable.setRowCount(0);

            while (rs.next()) {
                Vector columnDate = new Vector();

                for (i = 0; i <= q; i++) {
                    columnDate.add(rs.getString("StudentID"));
                    columnDate.add(rs.getString("Firstname"));
                    columnDate.add(rs.getString("Surname"));
                    columnDate.add(rs.getString("Address"));
                    columnDate.add(rs.getString("Gender"));
                    columnDate.add(rs.getString("DOB"));
                    columnDate.add(rs.getString("Mobile"));
                    columnDate.add(rs.getString("Email"));

                    columnDate.add(rs.getString("Course"));
                    columnDate.add(rs.getString("CourseCode"));

                    columnDate.add(rs.getString("Module1"));
                    columnDate.add(rs.getString("Module2"));
                    columnDate.add(rs.getString("Module3"));
                    columnDate.add(rs.getString("Module4"));
                    columnDate.add(rs.getString("Module5"));
                    columnDate.add(rs.getString("Module6"));
                    columnDate.add(rs.getString("Module7"));
                    columnDate.add(rs.getString("Module8"));

                    columnDate.add(rs.getString("Score1"));
                    columnDate.add(rs.getString("Score2"));
                    columnDate.add(rs.getString("Score3"));
                    columnDate.add(rs.getString("Score4"));
                    columnDate.add(rs.getString("Score5"));
                    columnDate.add(rs.getString("Score6"));
                    columnDate.add(rs.getString("Score7"));
                    columnDate.add(rs.getString("Score8"));

                    columnDate.add(rs.getString("TotalScore"));
                    columnDate.add(rs.getString("Ranking"));
                    columnDate.add(rs.getString("Date"));
                }

                RecordTable.addRow(columnDate);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtxtMabile = new javax.swing.JTextField();
        jtxtEmaile = new javax.swing.JTextField();
        jtxtDOB = new javax.swing.JTextField();
        jcboGender = new javax.swing.JComboBox<>();
        jtxtStudentID = new javax.swing.JTextField();
        jtxtSurname = new javax.swing.JTextField();
        jtxtAddress = new javax.swing.JTextField();
        jtxtFirstname = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jbtnExit = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnAdd = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        jbtnTranscript = new javax.swing.JButton();
        jbtnResult = new javax.swing.JButton();
        jtxtpanel = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxtTranscript = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtxtFacultyName = new javax.swing.JTextField();
        jtxtDean = new javax.swing.JTextField();
        jtxtCourseCode = new javax.swing.JTextField();
        jcboCourse = new javax.swing.JComboBox<>();
        jtxtLeader = new javax.swing.JTextField();
        jtxtTutor = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jtxtScore2 = new javax.swing.JTextField();
        jtxtScore1 = new javax.swing.JTextField();
        jtxtScore4 = new javax.swing.JTextField();
        jtxtScore3 = new javax.swing.JTextField();
        jtxtScore7 = new javax.swing.JTextField();
        jtxtScore8 = new javax.swing.JTextField();
        jtxtScore6 = new javax.swing.JTextField();
        jtxtScore5 = new javax.swing.JTextField();
        jtxtTotalScore = new javax.swing.JTextField();
        jtxtDate = new javax.swing.JTextField();
        jtxtRanking = new javax.swing.JTextField();
        jcboModule2 = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jComboBox10 = new javax.swing.JComboBox<>();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jComboBox11 = new javax.swing.JComboBox<>();
        jcboModule3 = new javax.swing.JComboBox<>();
        jcboModule4 = new javax.swing.JComboBox<>();
        jcboModule8 = new javax.swing.JComboBox<>();
        jcboModule7 = new javax.swing.JComboBox<>();
        jcboModule6 = new javax.swing.JComboBox<>();
        jcboModule5 = new javax.swing.JComboBox<>();
        jcboModule1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Email");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("Student ID");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("Firstname");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setText("Surname");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setText("Address");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setText("Gender");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setText("DOB");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setText("Mobile");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jtxtMabile.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jPanel3.add(jtxtMabile, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 220, -1));

        jtxtEmaile.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jPanel3.add(jtxtEmaile, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 220, -1));

        jtxtDOB.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jPanel3.add(jtxtDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 220, -1));

        jcboGender.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jcboGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "male", "female" }));
        jPanel3.add(jcboGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 220, 40));

        jtxtStudentID.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jPanel3.add(jtxtStudentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 220, -1));

        jtxtSurname.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jPanel3.add(jtxtSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 220, -1));

        jtxtAddress.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jPanel3.add(jtxtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 220, -1));

        jtxtFirstname.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jPanel3.add(jtxtFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 220, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 400, 350));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnExit.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, 110, -1));

        jbtnReset.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 110, -1));

        jbtnAdd.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jbtnAdd.setText("Add");
        jbtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 110, -1));

        btnPrint.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel4.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 110, -1));

        jbtnTranscript.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jbtnTranscript.setText("Transcript");
        jbtnTranscript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTranscriptActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnTranscript, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 170, -1));

        jbtnResult.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jbtnResult.setText("Result");
        jbtnResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResultActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 160, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 550, 880, 100));

        jtxtpanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jtxtpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jtxtpanel.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 420, 360));

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel10.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 420, 360));

        jtxtpanel.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 420, 450));

        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel12.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 420, 360));

        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel14.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 420, 360));

        jPanel12.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 420, 450));

        jtxtpanel.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 420, 450));

        jtxtTranscript.setColumns(20);
        jtxtTranscript.setRows(5);
        jScrollPane2.setViewportView(jtxtTranscript);

        jtxtpanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 410, 500));

        jPanel2.add(jtxtpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 430, 520));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setText("Course Tutor");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel11.setText("Dean of Faculty");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel12.setText("Faculty name");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel13.setText("Course code");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel14.setText("Course");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel10.setText("Program Leader");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jtxtFacultyName.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jPanel5.add(jtxtFacultyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 160, -1));

        jtxtDean.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jPanel5.add(jtxtDean, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 160, -1));

        jtxtCourseCode.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jPanel5.add(jtxtCourseCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 160, -1));

        jcboCourse.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jcboCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Course", "BA Animation", "BSc Computing", "BSc Computier Science", "BSc Computier  Animation", "BScSerios Games", "BSc Information System" }));
        jcboCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboCourseActionPerformed(evt);
            }
        });
        jPanel5.add(jcboCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 160, 40));

        jtxtLeader.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jPanel5.add(jtxtLeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 160, -1));

        jtxtTutor.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jPanel5.add(jtxtTutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 160, -1));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 400, 270));

        jPanel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel16.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 420, 360));

        jPanel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel18.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 420, 360));

        jPanel16.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 420, 450));

        jPanel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel20.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 420, 360));

        jPanel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel22.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 420, 360));

        jPanel20.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 420, 450));

        jPanel16.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 420, 450));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Score");
        jPanel16.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 100, -1));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("8");
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel16.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 30, -1));

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel24.setText("Date");
        jPanel16.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel25.setText("Ranking");
        jPanel16.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel26.setText("Total Score");
        jPanel16.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        jLabel28.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel28.setText("No");
        jPanel16.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel29.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Unit Selector");
        jPanel16.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 20, 240, -1));

        jtxtScore2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jtxtScore2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtScore2.setText("0");
        jtxtScore2.setEnabled(false);
        jtxtScore2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtScore2ActionPerformed(evt);
            }
        });
        jPanel16.add(jtxtScore2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 100, -1));

        jtxtScore1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jtxtScore1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtScore1.setText("0");
        jtxtScore1.setEnabled(false);
        jtxtScore1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtScore1ActionPerformed(evt);
            }
        });
        jPanel16.add(jtxtScore1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 100, -1));

        jtxtScore4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jtxtScore4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtScore4.setText("0");
        jtxtScore4.setEnabled(false);
        jtxtScore4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtScore4ActionPerformed(evt);
            }
        });
        jPanel16.add(jtxtScore4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 100, -1));

        jtxtScore3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jtxtScore3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtScore3.setText("0");
        jtxtScore3.setEnabled(false);
        jtxtScore3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtScore3ActionPerformed(evt);
            }
        });
        jPanel16.add(jtxtScore3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 100, -1));

        jtxtScore7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jtxtScore7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtScore7.setText("0");
        jtxtScore7.setEnabled(false);
        jtxtScore7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtScore7ActionPerformed(evt);
            }
        });
        jPanel16.add(jtxtScore7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 100, -1));

        jtxtScore8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jtxtScore8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtScore8.setText("0");
        jtxtScore8.setEnabled(false);
        jtxtScore8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtScore8ActionPerformed(evt);
            }
        });
        jPanel16.add(jtxtScore8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 100, -1));

        jtxtScore6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jtxtScore6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtScore6.setText("0");
        jtxtScore6.setEnabled(false);
        jtxtScore6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtScore6ActionPerformed(evt);
            }
        });
        jPanel16.add(jtxtScore6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 100, -1));

        jtxtScore5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jtxtScore5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtScore5.setText("0");
        jtxtScore5.setEnabled(false);
        jtxtScore5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtScore5ActionPerformed(evt);
            }
        });
        jPanel16.add(jtxtScore5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 100, -1));

        jtxtTotalScore.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jPanel16.add(jtxtTotalScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 250, -1));

        jtxtDate.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jPanel16.add(jtxtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, 250, -1));

        jtxtRanking.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jPanel16.add(jtxtRanking, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 250, -1));

        jcboModule2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jcboModule2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "SQL", "Database", "Speadsheet" }));
        jcboModule2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboModule2ActionPerformed(evt);
            }
        });
        jPanel16.add(jcboModule2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 240, 40));

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("1");
        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel16.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 30, -1));

        jLabel30.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("2");
        jLabel30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel16.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 30, -1));

        jLabel31.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("3");
        jLabel31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel16.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 30, -1));

        jLabel32.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("4");
        jLabel32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel16.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 30, -1));

        jLabel33.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("5");
        jLabel33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel16.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 30, -1));

        jLabel34.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("6");
        jLabel34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel16.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 30, -1));

        jLabel35.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("7");
        jLabel35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel16.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 30, -1));

        jPanel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel24.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 420, 360));

        jPanel26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel26.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 420, 360));

        jPanel24.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 420, 450));

        jPanel28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel28.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel29.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel28.add(jPanel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 420, 360));

        jPanel30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel30.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel31.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel30.add(jPanel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 420, 360));

        jPanel28.add(jPanel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 420, 450));

        jPanel24.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 420, 450));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel17.setText("jLabel1");
        jPanel24.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("8");
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel24.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 30, -1));

        jLabel27.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel27.setText("jLabel1");
        jPanel24.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        jLabel36.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel36.setText("jLabel1");
        jPanel24.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        jLabel37.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel37.setText("jLabel1");
        jPanel24.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        jLabel38.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel38.setText("jLabel1");
        jPanel24.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel39.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel39.setText("jLabel1");
        jPanel24.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        jTextField12.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jTextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField12.setText("0");
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        jPanel24.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 90, -1));

        jTextField13.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jTextField13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField13.setText("0");
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        jPanel24.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 90, -1));

        jTextField14.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jTextField14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField14.setText("0");
        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        jPanel24.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 90, -1));

        jTextField15.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jTextField15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField15.setText("0");
        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });
        jPanel24.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 90, -1));

        jTextField16.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jTextField16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField16.setText("0");
        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });
        jPanel24.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 90, -1));

        jTextField17.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jTextField17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField17.setText("0");
        jTextField17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField17ActionPerformed(evt);
            }
        });
        jPanel24.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 90, -1));

        jTextField18.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jTextField18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField18.setText("0");
        jTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField18ActionPerformed(evt);
            }
        });
        jPanel24.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 90, -1));

        jTextField19.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jTextField19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField19.setText("0");
        jTextField19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField19ActionPerformed(evt);
            }
        });
        jPanel24.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 90, -1));

        jTextField20.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jTextField20.setText("jTextField9");
        jPanel24.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, -1, -1));

        jTextField21.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jTextField21.setText("jTextField9");
        jPanel24.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, -1, -1));

        jTextField22.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jTextField22.setText("jTextField9");
        jPanel24.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, -1, -1));

        jComboBox10.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel24.add(jComboBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 240, 40));

        jLabel40.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("1");
        jLabel40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel24.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 30, -1));

        jLabel41.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("2");
        jLabel41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel24.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 30, -1));

        jLabel42.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("3");
        jLabel42.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel24.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 30, -1));

        jLabel43.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("4");
        jLabel43.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel24.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 30, -1));

        jLabel44.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("5");
        jLabel44.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel24.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 30, -1));

        jLabel45.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("6");
        jLabel45.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel24.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 30, -1));

        jLabel46.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("7");
        jLabel46.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel24.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 30, -1));

        jComboBox11.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel24.add(jComboBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 240, 40));

        jPanel16.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 430, 520));

        jcboModule3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jcboModule3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "System Analysis", "Network", "Inf Technology" }));
        jcboModule3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboModule3ActionPerformed(evt);
            }
        });
        jPanel16.add(jcboModule3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 240, 40));

        jcboModule4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jcboModule4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Statics", "Data Science", "Machine", "Artificial" }));
        jcboModule4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboModule4ActionPerformed(evt);
            }
        });
        jPanel16.add(jcboModule4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 240, 40));

        jcboModule8.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jcboModule8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "JavaScript", "Animation", "Graphic Design", "Digital Graphics" }));
        jcboModule8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboModule8ActionPerformed(evt);
            }
        });
        jPanel16.add(jcboModule8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 240, 40));

        jcboModule7.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jcboModule7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Matplotlib", "Raspberry Pi", "Cyber Security" }));
        jcboModule7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboModule7ActionPerformed(evt);
            }
        });
        jPanel16.add(jcboModule7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 240, 40));

        jcboModule6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jcboModule6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Object Oriented Programming", "Software Testing", "Procedural Programming" }));
        jcboModule6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboModule6ActionPerformed(evt);
            }
        });
        jPanel16.add(jcboModule6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 240, 40));

        jcboModule5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jcboModule5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "PHP Prog", "ComputerGames", "Web Site Deve" }));
        jcboModule5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboModule5ActionPerformed(evt);
            }
        });
        jPanel16.add(jcboModule5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 240, 40));

        jcboModule1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jcboModule1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Visual C++", "Python", "Java" }));
        jcboModule1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboModule1ActionPerformed(evt);
            }
        });
        jPanel16.add(jcboModule1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 240, 40));

        jPanel2.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 430, 520));

        jTabbedPane1.addTab("Universeti Records", jPanel2);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Student Result Management Systems");
        jPanel8.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1300, 110));

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Student ID", "FirstName", "Surname", "Address", "Gender", "DOB", "Module", "Email", "Course", "CourseCode", "Module1", "Module2", "Module3", "Module4", "Module5", "Module6", "Module7", "Module8", "Score1", "Score2", "Score3", "Score4", "Score5", "Score6", "Score7", "Score8", "TotalScore", "Ranking", "Date"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(jTable1);

        jPanel9.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1260, -1));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 1300, 520));

        jTabbedPane1.addTab("Student Records", jPanel1);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1340, 710));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtScore2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtScore2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtScore2ActionPerformed

    private void jtxtScore1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtScore1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtScore1ActionPerformed

    private void jtxtScore4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtScore4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtScore4ActionPerformed

    private void jtxtScore3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtScore3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtScore3ActionPerformed

    private void jtxtScore7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtScore7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtScore7ActionPerformed

    private void jtxtScore8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtScore8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtScore8ActionPerformed

    private void jtxtScore6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtScore6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtScore6ActionPerformed

    private void jtxtScore5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtScore5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtScore5ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void jTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField17ActionPerformed

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18ActionPerformed

    private void jTextField19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField19ActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        try {
            jtxtTranscript.print();
        } catch (java.awt.print.PrinterAbortException e) {
            System.err.format("No printer found", e.getMessage());
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit",
                "Student result systems", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        JTextField jtxt = null;
        JComboBox jcbo = null;
        for (Component c : jPanel3.getComponents()) {
            if (c.getClass().toString().contains("javax.swing.JTextField")) {
                jtxt = (JTextField) c;
                jtxt.setText(null);
            }
        }

        for (Component c : jPanel5.getComponents()) {
            if (c.getClass().toString().contains("javax.swing.JTextField")) {
                jtxt = (JTextField) c;
                jtxt.setText(null);
            }
        }

        for (Component c : jPanel16.getComponents()) {
            if (c.getClass().toString().contains("javax.swing.JComboBox")) {
                jcbo = (JComboBox) c;
                jcbo.setSelectedIndex(0);
            }
        }

        for (Component c : jPanel16.getComponents()) {
            if (c.getClass().toString().contains("javax.swing.JTextField")) {
                jtxt = (JTextField) c;
                jtxt.setText("0");
            }
        }

        jtxtTranscript.setText(null);
        jcboGender.setSelectedIndex(0);
        jcboCourse.setSelectedIndex(0);
        jtxtTotalScore.setText(null);
        jtxtRanking.setText(null);
        jtxtDate.setText(null);
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResultActionPerformed
        int[] score = new int[9];
        score[0] = Integer.parseInt(jtxtScore1.getText());
        score[1] = Integer.parseInt(jtxtScore2.getText());
        score[2] = Integer.parseInt(jtxtScore3.getText());
        score[3] = Integer.parseInt(jtxtScore4.getText());
        score[4] = Integer.parseInt(jtxtScore5.getText());
        score[5] = Integer.parseInt(jtxtScore6.getText());
        score[6] = Integer.parseInt(jtxtScore7.getText());
        score[7] = Integer.parseInt(jtxtScore8.getText());

        score[8] = score[0] + score[1] + score[2] + score[3] + score[4]
                + score[5] + score[6] + score[7];

        jtxtTotalScore.setText(Integer.toString(score[8]));

        if (score[8] >= 700) {
            jtxtRanking.setText("1st Class");
        } else if (score[8] >= 600) {
            jtxtRanking.setText("2i Class Upper");
        } else if (score[8] >= 500) {
            jtxtRanking.setText("2ii Class Lower");
        } else if (score[8] >= 400) {
            jtxtRanking.setText("3rd Class");
        } else if (score[8] >= 300) {
            jtxtRanking.setText("CoHE");
        } else if (score[8] <= 299) {
            jtxtRanking.setText("Fail");
        }

        Calendar ToDay = Calendar.getInstance();
        ToDay.getTime();
        SimpleDateFormat Tdate = new SimpleDateFormat("dd-MMM-yyyy");
        jtxtDate.setText(Tdate.format(ToDay.getTime()));

        if (score[0] > 100) {
            jtxtScore1.setText("0");
        }
        if (score[1] > 100) {
            jtxtScore2.setText("0");
        }
        if (score[2] > 100) {
            jtxtScore3.setText("0");
        }
        if (score[3] > 100) {
            jtxtScore4.setText("0");
        }
        if (score[4] > 100) {
            jtxtScore5.setText("0");
        }
        if (score[5] > 100) {
            jtxtScore6.setText("0");
        }
        if (score[6] > 100) {
            jtxtScore7.setText("0");
        }
        if (score[7] > 100) {
            jtxtScore8.setText("0");
        }

    }//GEN-LAST:event_jbtnResultActionPerformed

    private void jbtnTranscriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTranscriptActionPerformed
        jtxtTranscript.append("\t\t Transcript \n"
                + "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\n"
                + "Student Registration Number:\t\t" + jtxtStudentID.getText() + "\n\n"
                + "Name: " + "\t" + jtxtFirstname.getText() + "\t" + jtxtSurname.getText() + "\n\n"
                + "1: " + jcboModule1.getSelectedItem() + "\t\t\t" + jtxtScore1.getText() + "\n\n"
                + "2: " + jcboModule2.getSelectedItem() + "\t\t\t" + jtxtScore2.getText() + "\n\n"
                + "3: " + jcboModule3.getSelectedItem() + "\t\t\t" + jtxtScore3.getText() + "\n\n"
                + "4: " + jcboModule4.getSelectedItem() + "\t\t\t" + jtxtScore4.getText() + "\n\n"
                + "5: " + jcboModule5.getSelectedItem() + "\t\t\t" + jtxtScore5.getText() + "\n\n"
                + "6: " + jcboModule6.getSelectedItem() + "\t\t\t" + jtxtScore6.getText() + "\n\n"
                + "7: " + jcboModule7.getSelectedItem() + "\t\t\t" + jtxtScore7.getText() + "\n\n"
                + "8: " + jcboModule8.getSelectedItem() + "\t\t\t" + jtxtScore8.getText() + "\n\n"
                + "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\n"
                + "Total Score: \t\t" + jtxtTotalScore.getText() + "\n"
                + "Ranking: \t\t" + jtxtRanking.getText() + "\n"
                + "Date: \t\t" + jtxtDate.getText() + "\n"
        );
    }//GEN-LAST:event_jbtnTranscriptActionPerformed

    private void jcboModule1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboModule1ActionPerformed
        if (jcboModule1.getSelectedItem().equals("")) {
            jtxtScore1.setText("0");
            jtxtScore1.setEnabled(false);
        } else {
            jtxtScore1.setText("0");
            jtxtScore1.setEnabled(true);
            jtxtScore1.requestFocus();
        }
    }//GEN-LAST:event_jcboModule1ActionPerformed

    private void jcboModule2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboModule2ActionPerformed
        if (jcboModule2.getSelectedItem().equals("")) {
            jtxtScore2.setText("0");
            jtxtScore2.setEnabled(false);
        } else {
            jtxtScore2.setText("0");
            jtxtScore2.setEnabled(true);
            jtxtScore2.requestFocus();
        }
    }//GEN-LAST:event_jcboModule2ActionPerformed

    private void jcboModule3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboModule3ActionPerformed
        if (jcboModule3.getSelectedItem().equals("")) {
            jtxtScore3.setText("0");
            jtxtScore3.setEnabled(false);
        } else {
            jtxtScore3.setText("0");
            jtxtScore3.setEnabled(true);
            jtxtScore3.requestFocus();
        }
    }//GEN-LAST:event_jcboModule3ActionPerformed

    private void jcboModule4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboModule4ActionPerformed
        if (jcboModule4.getSelectedItem().equals("")) {
            jtxtScore4.setText("0");
            jtxtScore4.setEnabled(false);
        } else {
            jtxtScore4.setText("0");
            jtxtScore4.setEnabled(true);
            jtxtScore4.requestFocus();
        }
    }//GEN-LAST:event_jcboModule4ActionPerformed

    private void jcboModule5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboModule5ActionPerformed
        if (jcboModule5.getSelectedItem().equals("")) {
            jtxtScore5.setText("0");
            jtxtScore5.setEnabled(false);
        } else {
            jtxtScore5.setText("0");
            jtxtScore5.setEnabled(true);
            jtxtScore5.requestFocus();
        }
    }//GEN-LAST:event_jcboModule5ActionPerformed

    private void jcboModule6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboModule6ActionPerformed
        if (jcboModule6.getSelectedItem().equals("")) {
            jtxtScore6.setText("0");
            jtxtScore6.setEnabled(false);
        } else {
            jtxtScore6.setText("0");
            jtxtScore6.setEnabled(true);
            jtxtScore6.requestFocus();
        }
    }//GEN-LAST:event_jcboModule6ActionPerformed

    private void jcboModule7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboModule7ActionPerformed
        if (jcboModule7.getSelectedItem().equals("")) {
            jtxtScore7.setText("0");
            jtxtScore7.setEnabled(false);
        } else {
            jtxtScore7.setText("0");
            jtxtScore7.setEnabled(true);
            jtxtScore7.requestFocus();
        }
    }//GEN-LAST:event_jcboModule7ActionPerformed

    private void jcboModule8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboModule8ActionPerformed
        if (jcboModule8.getSelectedItem().equals("")) {
            jtxtScore8.setText("0");
            jtxtScore8.setEnabled(false);
        } else {
            jtxtScore8.setText("0");
            jtxtScore8.setEnabled(true);
            jtxtScore8.requestFocus();
        }
    }//GEN-LAST:event_jcboModule8ActionPerformed

    private void jcboCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboCourseActionPerformed

        if (jcboCourse.getSelectedItem().equals("BA Animation")) {
            jtxtCourseCode.setText("BA0895");
            jtxtFacultyName.setText("School of Art");
            jtxtDean.setText("Prof. Georg Vi");
            jtxtLeader.setText("Dr. Kerry Casy");
            jtxtTutor.setText("Dr. Tony Anthony");
        } else if (jcboCourse.getSelectedItem().equals("BSc Computing")) {
            jtxtCourseCode.setText("BC80895");
            jtxtFacultyName.setText("School of Art");
            jtxtDean.setText("Prof. Toy Vi");
            jtxtLeader.setText("Dr. Dert Casy");
            jtxtTutor.setText("Dr. Nik Anthony");
        } else if (jcboCourse.getSelectedItem().equals("BSc Computier Science")) {
            jtxtCourseCode.setText("BCS80695");
            jtxtFacultyName.setText("School of Art");
            jtxtDean.setText("Prof. Nik Vi");
            jtxtLeader.setText("Dr. Toy Casy");
            jtxtTutor.setText("Dr. Nik Anthony");
        } else if (jcboCourse.getSelectedItem().equals("BSc Computier  Animation")) {
            jtxtCourseCode.setText("BCA80699");
            jtxtFacultyName.setText("School of Art");
            jtxtDean.setText("Prof. Nik Vtryi");
            jtxtLeader.setText("Dr. Tom Casy");
            jtxtTutor.setText("Dr. Nikol Anthony");
        } else if (jcboCourse.getSelectedItem().equals("BScSerios Games")) {
            jtxtCourseCode.setText("BG80679");
            jtxtFacultyName.setText("School of Art");
            jtxtDean.setText("Prof. Max Tray");
            jtxtLeader.setText("Dr. Tom Casy");
            jtxtTutor.setText("Dr. Nikol Pachin");
        } else if (jcboCourse.getSelectedItem().equals("BSc Information System")) {
            jtxtCourseCode.setText("BIS80559");
            jtxtFacultyName.setText("School of Art");
            jtxtDean.setText("Prof. Max Casy");
            jtxtLeader.setText("Dr. Tomas Retus");
            jtxtTutor.setText("Dr. Alis Vera");
        } else if (jcboCourse.getSelectedItem().equals("Select a Course")) {
            JTextField jtxt = null;
            for (Component c : jPanel5.getComponents()) {
                if (c.getClass().toString().contains("javax.swing.JTextField")) {
                    jtxt = (JTextField) c;
                    jtxt.setText(null);
                }
            }

        }


    }//GEN-LAST:event_jcboCourseActionPerformed

    private void jbtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlCon = DriverManager.getConnection(dataCon, username, password);
            pst = sqlCon.prepareStatement("insert into resultdb(StudentID, Firstname, Surname, Address, Gender,"
                    + "DOB, Mobile, Email, Course, CourseCode,"
                    + "Module1, Module2,Module3,Module4,Module5,Module6,Module7,Module8,"
                    + "Score1,Score2,Score3,Score4,Score5,Score6,Score7,Score8,"
                    + "TotalScore, Ranking, Date)" + "value(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");

            pst.setString(1, jtxtStudentID.getText());
            pst.setString(2, jtxtFirstname.getText());
            pst.setString(3, jtxtSurname.getText());
            pst.setString(4, jtxtAddress.getText());
            pst.setString(5, (String) jcboGender.getSelectedItem());
            pst.setString(6, jtxtDOB.getText());
            pst.setString(7, jtxtMabile.getText());
            pst.setString(8, jtxtEmaile.getText());
            pst.setString(9, (String) jcboCourse.getSelectedItem());
            pst.setString(10, jtxtCourseCode.getText());

            pst.setString(11, (String) jcboModule1.getSelectedItem());
            pst.setString(12, (String) jcboModule2.getSelectedItem());
            pst.setString(13, (String) jcboModule3.getSelectedItem());
            pst.setString(14, (String) jcboModule4.getSelectedItem());
            pst.setString(15, (String) jcboModule5.getSelectedItem());
            pst.setString(16, (String) jcboModule6.getSelectedItem());
            pst.setString(17, (String) jcboModule7.getSelectedItem());
            pst.setString(18, (String) jcboModule8.getSelectedItem());

            pst.setString(19, (String) jtxtScore1.getText());
            pst.setString(20, (String) jtxtScore2.getText());
            pst.setString(21, (String) jtxtScore3.getText());
            pst.setString(22, (String) jtxtScore4.getText());
            pst.setString(23, (String) jtxtScore5.getText());
            pst.setString(24, (String) jtxtScore6.getText());
            pst.setString(25, (String) jtxtScore7.getText());
            pst.setString(26, (String) jtxtScore8.getText());

            pst.setString(27, (String) jtxtTotalScore.getText());
            pst.setString(28, (String) jtxtRanking.getText());
            pst.setString(29, (String) jtxtDate.getText());

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Student Result Updated");
            uploadDB();

        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_BD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(Student_BD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtnAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_BD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_BD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_BD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_BD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_BD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrint;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox11;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JButton jbtnAdd;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnResult;
    private javax.swing.JButton jbtnTranscript;
    private javax.swing.JComboBox<String> jcboCourse;
    private javax.swing.JComboBox<String> jcboGender;
    private javax.swing.JComboBox<String> jcboModule1;
    private javax.swing.JComboBox<String> jcboModule2;
    private javax.swing.JComboBox<String> jcboModule3;
    private javax.swing.JComboBox<String> jcboModule4;
    private javax.swing.JComboBox<String> jcboModule5;
    private javax.swing.JComboBox<String> jcboModule6;
    private javax.swing.JComboBox<String> jcboModule7;
    private javax.swing.JComboBox<String> jcboModule8;
    private javax.swing.JTextField jtxtAddress;
    private javax.swing.JTextField jtxtCourseCode;
    private javax.swing.JTextField jtxtDOB;
    private javax.swing.JTextField jtxtDate;
    private javax.swing.JTextField jtxtDean;
    private javax.swing.JTextField jtxtEmaile;
    private javax.swing.JTextField jtxtFacultyName;
    private javax.swing.JTextField jtxtFirstname;
    private javax.swing.JTextField jtxtLeader;
    private javax.swing.JTextField jtxtMabile;
    private javax.swing.JTextField jtxtRanking;
    private javax.swing.JTextField jtxtScore1;
    private javax.swing.JTextField jtxtScore2;
    private javax.swing.JTextField jtxtScore3;
    private javax.swing.JTextField jtxtScore4;
    private javax.swing.JTextField jtxtScore5;
    private javax.swing.JTextField jtxtScore6;
    private javax.swing.JTextField jtxtScore7;
    private javax.swing.JTextField jtxtScore8;
    private javax.swing.JTextField jtxtStudentID;
    private javax.swing.JTextField jtxtSurname;
    private javax.swing.JTextField jtxtTotalScore;
    private javax.swing.JTextArea jtxtTranscript;
    private javax.swing.JTextField jtxtTutor;
    private javax.swing.JPanel jtxtpanel;
    // End of variables declaration//GEN-END:variables
}
